version: "3.7"
services:
  bot-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: bot
    networks:
      - bot-network
  app:
    build: .
    networks:
      - bot-network
    expose:
      - '8080/tcp'
networks:
  bot-network:
